name: CI Pipeline
permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ${{secrets.APP_DB}}
          POSTGRES_USER: ${{secrets.APP_DB_USER}}
          POSTGRES_PASSWORD: ${{secrets.APP_DB_PASSWORD}}
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"
          cache: "maven"
          cache-dependency-path: Phase1-Group-Projects/6-InsightFlow/backend/pom.xml
      - run: mvn clean package -DskipTests
        working-directory: ./Phase1-Group-Projects/6-InsightFlow/backend
      - run: mvn test
        working-directory: ./Phase1-Group-Projects/6-InsightFlow/backend
        env:
          APP_DB_URL: jdbc:postgresql://localhost:5432/${{secrets.APP_DB}}
          APP_DB_USER: ${{secrets.APP_DB_USER}}
          APP_DB_PASSWORD: ${{secrets.APP_DB_PASSWORD}}
          APP_JWT_SECRET: ${{secrets.APP_JWT_SECRET}}
          APP_ACCESS_TOKEN_EXPIRATION: ${{secrets.APP_ACCESS_TOKEN_EXPIRATION}}
          APP_REFRESH_TOKEN_EXPIRATION: ${{secrets.APP_REFRESH_TOKEN_EXPIRATION}}

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Phase1-Group-Projects/6-InsightFlow/frontend

    env:
      BACKEND_URL: http://localhost:8080
      COOKIE_NAME: ${{secrets.FRONTEND_COOKIE_NAME}}
      COOKIE_KEY: ${{ secrets.FRONTEND_COOKIE_KEY }}
      COOKIE_EXPIRY_DAYS: ${{ secrets.FRONTEND_COOKIE_EXPIRY_DAYS }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check for syntax errors
        run: python -m py_compile app.py pages/*.py utils/*.py components/*.py

      - name: Run linter
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv,.venv,__pycache__,.git
